version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: todo_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db/mongodb/database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped