version: "3.4"
services:
  todo_api:
    build: 
      context: .
      target: local
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: todo_api
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    env_file: .env
  mongodb:
    image: mongo
    container_name: todo_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db/mongodb/database:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    restart: unless-stopped